data_drift:
  # general
  threshold: 3

  internal_data_drift_detector:
    # general
    weight: 3

    # approach thresholds
    model_based_threshold: 1e-1
    statistical_based_threshold: .3  # at least one is detected

    # feature thresholds
    mean:
      threshold: 1e-1
      percent_of_features: 1e-1  # number of features the indicates on data drift
      weight: .33333
    variance:
      threshold: 1e-1
      percent_of_features: 1e-1  # number of features the indicates on data drift
      weight: .33333
    number_of_nulls:
      threshold: 5
      percent_of_features: 1e-1  # number of features the indicates on data drift
      weight: .33333

  tensorflow_data_validation:
    weight: 1

  scikit_multiflow:
    weight: 1