data_drift:
  # general
  threshold: 3

  internal_data_drift_detector:
    # general
    weight: 3

    # approach thresholds
    model_based_threshold: 1e-1
    statistical_based_threshold: .3  # at least one is detected

    # feature thresholds
    mean:
      percent_threshold: 1e-1  # percent of change
      percent_of_features: 1e-1  # number of features that indicates on a data drift
      weight: .33333
    variance:
      percent_threshold: 1e-1   # percent of change
      percent_of_features: 1e-1  # number of features that indicates on a data drift
      weight: .33333
    number_of_nulls:
      percent_threshold: 1e-1  # percent of change
      percent_of_features: 1e-1  # number of features that indicates on a data drift
      weight: .33333

  tensorflow_data_validation:
    weight: 1

  scikit_multiflow:
    weight: 1
    total_weight: 1  # because of this overlapping doesn't enforce data drift
    weight_on_overlapping_instances: 5e-1
    percent_on_overlapping_instances: 1e-1
    modules:
      DDM:
        weight: 1
        percent_of_instances: 1e-1  # number of instances that indicates on a data drift
      EDDM:
        weight: 1
        percent_of_instances: 1e-1  # number of instances that indicates on a data drift
      HDDM_A:
        weight: 1
        percent_of_instances: 1e-1  # number of instances that indicates on a data drift
      HDDM_W:
        weight: 1
        percent_of_instances: 1e-1  # number of instances that indicates on a data drift

data_generation:
  data_drift:
    generation_percent: 200  # means to generate a dataset of double size
    variance:
      features: ["feature_1", "...", "feature_k"]
    mean:
      features: ["feature_1", "...", "feature_k"]
    number_of_nulls:
      features: ["feature_1", "...", "feature_k"]